micronaut:
  http:
    services:
      simple2:
        url: http://localhost:8081
        path: /simple/c2
      simple3:
        url: http://localhost:8081 
        path: /simple/c3
      simple5:
        url: http://localhost:8081
simple6_host: localhost:8081       
simple6_base_path: simple/c6
## completion for services: url and path are not available in completion for simple3, since they are already set for simple2 